<?php
/**
 * Upsell banner and upgrade modal for free-tier users.
 *
 * @package SEOAutowrite_Pro
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SEOAPW_Upsell {

	// -------------------------------------------------------------------------
	// Init
	// -------------------------------------------------------------------------

	public static function init(): void {
		add_action( 'seoapw_admin_header_after_title', array( __CLASS__, 'render_upsell_banner' ) );
		add_action( 'seoapw_before_settings_form',     array( __CLASS__, 'render_upgrade_modal' ) );
	}

	// -------------------------------------------------------------------------
	// Upsell banner (shown in header when no Pro license)
	// -------------------------------------------------------------------------

	public static function render_upsell_banner(): void {
		if ( seoapw_is_pro() ) {
			return;
		}

		$buy_url = SEOAPW_API_URL . '/topup';
		?>
		<div class="seoapw-upsell-banner">
			<span class="seoapw-upsell-banner__text">
				<?php esc_html_e( 'You\'re on the free plan — articles generated by Ollama. Upgrade to Pro for SEOAutowrite AI articles from $1.50/article. Start with $5.', 'seoapw' ); ?>
			</span>
			<button type="button" id="seoapw-open-upgrade-modal" class="seoapw-upsell-banner__btn">
				<?php esc_html_e( 'Upgrade to Pro', 'seoapw' ); ?>
			</button>
		</div>
		<?php
	}

	// -------------------------------------------------------------------------
	// Upgrade modal
	// -------------------------------------------------------------------------

	public static function render_upgrade_modal(): void {
		if ( seoapw_is_pro() ) {
			return;
		}

		$buy_url = SEOAPW_API_URL . '/get-started';
		?>
		<div id="seoapw-upgrade-modal" class="seoapw-modal" style="display:none;" role="dialog" aria-modal="true" aria-labelledby="seoapw-modal-title">
			<div class="seoapw-modal__backdrop"></div>
			<div class="seoapw-modal__content">

				<button type="button" class="seoapw-modal__close" aria-label="<?php esc_attr_e( 'Close', 'seoapw' ); ?>">&times;</button>

				<h2 id="seoapw-modal-title"><?php esc_html_e( 'Upgrade to SEOAutowrite Pro', 'seoapw' ); ?></h2>
				<p class="seoapw-modal__subtitle">
					<?php esc_html_e( 'SEOAutowrite AI articles. No subscription. Pay only for what you publish.', 'seoapw' ); ?>
				</p>

				<table class="seoapw-comparison">
					<thead>
						<tr>
							<th><?php esc_html_e( 'Feature', 'seoapw' ); ?></th>
							<th><?php esc_html_e( 'Free (Ollama)', 'seoapw' ); ?></th>
							<th class="seoapw-comparison__pro"><?php esc_html_e( 'Pro (SEOAutowrite AI)', 'seoapw' ); ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><?php esc_html_e( 'Article quality', 'seoapw' ); ?></td>
							<td><?php esc_html_e( 'Good', 'seoapw' ); ?></td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( 'World-class', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'AI model', 'seoapw' ); ?></td>
							<td><?php esc_html_e( 'Local Ollama model', 'seoapw' ); ?></td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( 'SEOAutowrite AI', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'E-E-A-T optimisation', 'seoapw' ); ?></td>
							<td><?php esc_html_e( 'Basic', 'seoapw' ); ?></td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( 'Advanced (Phase 1 analysis)', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Server-side prompt', 'seoapw' ); ?></td>
							<td>&mdash;</td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( 'Hidden, optimised by us', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Semantic keyword strategy', 'seoapw' ); ?></td>
							<td>&mdash;</td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( '✓ Woven in naturally', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Featured image generation', 'seoapw' ); ?></td>
							<td><?php esc_html_e( 'DALL·E (basic prompt)', 'seoapw' ); ?></td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( 'Precision image generation', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Auto top-up', 'seoapw' ); ?></td>
							<td>&mdash;</td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( '✓ Never miss a scheduled run', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Low balance alerts', 'seoapw' ); ?></td>
							<td>&mdash;</td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( '✓ Email alerts', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Cost', 'seoapw' ); ?></td>
							<td><?php esc_html_e( 'Free (self-hosted)', 'seoapw' ); ?></td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( '$1.50 / article', 'seoapw' ); ?></td>
						</tr>
						<tr>
							<td><?php esc_html_e( 'Minimum balance', 'seoapw' ); ?></td>
							<td>&mdash;</td>
							<td class="seoapw-comparison__pro"><?php esc_html_e( '$5.00 to start', 'seoapw' ); ?></td>
						</tr>
					</tbody>
				</table>

				<div class="seoapw-modal__cta">
					<a href="<?php echo esc_url( $buy_url ); ?>" target="_blank" class="seoapw-btn-primary">
						<?php esc_html_e( 'Buy $5 Balance →', 'seoapw' ); ?>
					</a>
					<p class="seoapw-modal__cta-note">
						<?php esc_html_e( 'You\'ll receive a license key by email. Enter it in the License section above to activate Pro.', 'seoapw' ); ?>
					</p>
				</div>

			</div>
		</div>
		<?php
	}
}

SEOAPW_Upsell::init();
